//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Colaborador> Colaborador { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Prioridad> Prioridad { get; set; }
        public DbSet<Tarea> Tarea { get; set; }
    
        public virtual ObjectResult<obtenerTareaFiltro_Result> obtenerTareaFiltro(Nullable<System.DateTime> fecha_inicio, Nullable<System.DateTime> fecha_fin, Nullable<int> id_colaborador, string codigo_estado, string codigo_prioridad)
        {
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            var id_colaboradorParameter = id_colaborador.HasValue ?
                new ObjectParameter("id_colaborador", id_colaborador) :
                new ObjectParameter("id_colaborador", typeof(int));
    
            var codigo_estadoParameter = codigo_estado != null ?
                new ObjectParameter("codigo_estado", codigo_estado) :
                new ObjectParameter("codigo_estado", typeof(string));
    
            var codigo_prioridadParameter = codigo_prioridad != null ?
                new ObjectParameter("codigo_prioridad", codigo_prioridad) :
                new ObjectParameter("codigo_prioridad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<obtenerTareaFiltro_Result>("obtenerTareaFiltro", fecha_inicioParameter, fecha_finParameter, id_colaboradorParameter, codigo_estadoParameter, codigo_prioridadParameter);
        }
    }
}
