//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int id_tarea { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_colaborador { get; set; }
        public string codigo_estado { get; set; }
        public string codigo_prioridad { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public string nota { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Prioridad Prioridad { get; set; }
    }
}
